name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - infra/runner-toevoegen

  pull_request:
    branches:
      - main
      - develop
      - feature_UC12
      - feature_UC14

jobs:
  build:
    runs-on: windows-latest  # Of windows-latest/macOS-latest als specifiek platform nodig is
    steps:
      
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Installeer .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: MAUI Workload installeren
        run: dotnet workload install maui

      - name: NuGet packages herstellen
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Voer unit tests uit
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
